# ===============================
# CONFIGURAZIONE GENERALE APP
# ===============================

spring.application.name=demo
# Nome dell'applicazione Spring Boot

server.port=8081
# Porta backend (http://localhost:8081)


# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/ticketing_itconsulting?createDatabaseIfNotExist=true
# Connessione MySQL + creazione DB automatica se non esiste

spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
# aggiorna automaticamente schema DB (solo DEV)

spring.jpa.show-sql=true
# stampa query SQL in console


# ===============================
# EMAIL SMTP
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_EMAIL@gmail.com
spring.mail.password=YOUR_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true